### ISSUE TITLE
Doesn't work well w/ blender2.8

### ISSUE THREAD

**Issue by StarrKiss** [dracula/blender#1]
![image](https://user-images.githubusercontent.com/13007697/63782773-86551400-c8b1-11e9-9a01-54f06ae13d10.png)

Some parts of the UI are dark grey, others match the dracula theme.

**Comment by ChildishGiant** [comment]
I've not actively worked on this theme in a while but I'll add this to my todo list 😄

**Comment by Blenux** [comment]
If one still needs a 2.80+ version, I've done some fixes.
