### ISSUE TITLE
any plan to update for 3.x ?

### ISSUE THREAD

**Issue by S1U** [dracula/blender#4]
<img width="1249" alt="Screen Shot 2022-05-28 at 13 54 04" src="https://user-images.githubusercontent.com/4564129/170812233-43f2eccd-acef-4724-aef0-eccb35bb0f92.png">

**Comment by lowpolygon-design** [comment]
Nice! I've also been working on a dracula theme as well. https://github.com/lowpolygon-design/blender3.0-dracula

**Comment by S1U** [comment]
fantastic! thanks!

- Junbro

**Comment by foxtrot222** [comment]
It's updated now
